---
# Passwords
ansible_become_password: '{{lookup("passwordstore", "hosts/admin-pass")}}'
bootstrap__admin_pass: '{{lookup("vault", "users", field="admin", stage="all", env="all")}}'
bootstrap__root_pass:  '{{lookup("vault", "users", field="root",  stage="all", env="all")}}'
bootstrap__active_users_passwords: '{{ bootstrap__active_users | get_user_passwords }}'
# Consul
bootstrap__consul_encryption_key:   '{{lookup("vault", "config",            field="consul-encryption-key", stage="all", env="all")}}'
bootstarp__consul_agent_acl_token:  '{{lookup("vault", "consul/acl-tokens", field="agent-default",         stage="all", env="all")}}'
bootstrap__consul_certs_ca_crt:     '{{lookup("vault", "consul/certs",      field="ca.pem",                stage="all", env="all")}}'
bootstrap__consul_certs_client_crt: '{{lookup("vault", "consul/certs",      field="client.pem",            stage="all", env="all")}}'
bootstrap__consul_certs_client_key: '{{lookup("vault", "consul/certs",      field="client-key.pem",        stage="all", env="all")}}'
# SSHGuard
bootstrap__sshguard_whitelist_extra: ['{{lookup("vault", "sshguard/whitelist",    field="jakubgs-home",    stage="all", env="all")}}']
# Wireguard
wireguard_consul_acl_token:         '{{lookup("vault", "consul/acl-tokens", field="wireguard",             stage="all", env="all")}}'

# Wazuh Agent
wazuh_agent_enrollment_key:         '{{ lookup("vault", "manager/config", field="enrollment-password", env="hq", stage="wazuh")}}'
wazuh_root_ca:                      '{{ lookup("vault", "root-ca",        field="certificate",         env="hq", stage="wazuh")}}'

# Vault certificate
bootstrap__vault_ca_cert:           '{{ lookup("passwordstore", "services/vault/certs/root-ca/cert returnall=true")}}'
bootstrap__vault_client_cert:       '{{ lookup("passwordstore", "services/vault/certs/client-host/cert returnall=true")}}'
bootstrap__vault_client_key:        '{{ lookup("passwordstore", "services/vault/certs/client-host/privkey returnall=true")}}'
