---
- name: Cleanup to regain disk space
  hosts: all
  tasks:
    - name: Save current available space
      set_fact:
        free_before: |
          {{ ansible_mounts
           | selectattr("mount", "equalto", "/")
           | map(attribute="size_available")
           | first }}

    - name: Clean apt packages
      apt:
        autoremove: true
        purge: true

    - name: Remove snapd files
      file:
        path: '/var/lib/snapd'
        state: absent

    - name: Remove logs older than 1 day
      command: |
        journalctl --vacuum-time=1d

    - name: Remove gzipped log archives
      shell: |
        rm -f \
          /var/log/*.gz \
          /var/log/docker/*/*.gz \
          /var/log/service/*/*.gz

    - name: Prune Docker leftover data
      command: |
        docker system prune -f -a --volumes

    - name: Gather space info
      when: ansible_system == "Linux"
      setup: gather_subset=mounts

    - name: Save available space
      when: ansible_system == "Linux"
      set_fact:
        free_after: |
          {{ ansible_mounts
           | selectattr("mount", "equalto", "/")
           | map(attribute="size_available")
           | first }}

    - name: Show space recovered
      when: ansible_system == "Linux"
      debug:
        msg: '~ {{ ((free_after|int - free_before|int)/(1024*1024)) | round | int }} MB'
